/**
 * Additional color maps generated by https://github.com/niivue/fs2NiiVueColormaps,
 * with a few fixes.
 */

/**
 * Full `FreeSurferColorLUT.txt` label color map.
 */
import FreeSurferColorLUT from "./FreeSurferColorLUT.json";

Object.freeze(FreeSurferColorLUT);

export { FreeSurferColorLUT };
